"""fix the db drift and sync schema

Revision ID: 0027_fix_the_db_drift_and_sync_s
Revises: 0026_add_status_for_files
Create Date: 2026-04-13 15:58:05.065293

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from alembic_postgresql_enum import TableReference
from sqlalchemy.dialects import postgresql
import sqlmodel

# revision identifiers, used by Alembic.
revision: str = '0027_fix_the_db_drift_and_sync_s'
down_revision: Union[str, Sequence[str], None] = '0026_add_status_for_files'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_lesplan_feedback_message_request_id'), table_name='lesplan_feedback_message')
    op.drop_table('lesplan_feedback_message')
    op.drop_constraint(op.f('fk_book_subject_id_subject'), 'book', type_='foreignkey')
    op.create_foreign_key(None, 'book', 'subjects', ['subject_id'], ['id'])
    op.drop_column('book_chapter', 'toets_url')
    op.alter_column('class', 'class_notes',
               existing_type=sa.TEXT(),
               type_=sqlmodel.sql.sqltypes.AutoString(),
               existing_nullable=True)
    op.drop_constraint(op.f('class_user_id_fkey'), 'class', type_='foreignkey')
    op.create_foreign_key(None, 'class', 'user', ['user_id'], ['id'])
    op.alter_column('file', 'extracted_text',
               existing_type=sa.TEXT(),
               type_=sqlmodel.sql.sqltypes.AutoString(),
               existing_nullable=True)
    op.drop_constraint(op.f('uq_lesplan_overview_request_id'), 'lesplan_overview', type_='unique')
    op.drop_constraint(op.f('lesplan_overview_request_id_fkey'), 'lesplan_overview', type_='foreignkey')
    op.create_foreign_key(None, 'lesplan_overview', 'lesplan_request', ['request_id'], ['id'])
    op.drop_constraint(op.f('lesplan_request_user_id_fkey'), 'lesplan_request', type_='foreignkey')
    op.drop_constraint(op.f('lesplan_request_class_id_fkey'), 'lesplan_request', type_='foreignkey')
    op.create_foreign_key(None, 'lesplan_request', 'user', ['user_id'], ['id'])
    op.create_foreign_key(None, 'lesplan_request', 'class', ['class_id'], ['id'])
    op.drop_constraint(op.f('lesson_plan_overview_id_fkey'), 'lesson_plan', type_='foreignkey')
    op.create_foreign_key(None, 'lesson_plan', 'lesplan_overview', ['overview_id'], ['id'])
    op.drop_constraint(op.f('lesson_preparation_todo_lesson_plan_id_fkey'), 'lesson_preparation_todo', type_='foreignkey')
    op.create_foreign_key(None, 'lesson_preparation_todo', 'lesson_plan', ['lesson_plan_id'], ['id'])
    op.drop_constraint(op.f('subjects_slug_key'), 'subjects', type_='unique')
    op.sync_enum_values(
        enum_schema='public',
        enum_name='class_support_challenge',
        new_values=['MORE_SUPPORT', 'BALANCED', 'MORE_CHALLENGE'],
        affected_columns=[TableReference(table_schema='public', table_name='class', column_name='support_challenge')],
        enum_values_to_rename=[],
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.sync_enum_values(
        enum_schema='public',
        enum_name='class_support_challenge',
        new_values=['Meer ondersteuning', 'Gebalanceerd', 'Meer uitdaging'],
        affected_columns=[TableReference(table_schema='public', table_name='class', column_name='support_challenge')],
        enum_values_to_rename=[],
    )
    op.create_unique_constraint(op.f('subjects_slug_key'), 'subjects', ['slug'], postgresql_nulls_not_distinct=False)
    op.drop_constraint(None, 'lesson_preparation_todo', type_='foreignkey')
    op.create_foreign_key(op.f('lesson_preparation_todo_lesson_plan_id_fkey'), 'lesson_preparation_todo', 'lesson_plan', ['lesson_plan_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint(None, 'lesson_plan', type_='foreignkey')
    op.create_foreign_key(op.f('lesson_plan_overview_id_fkey'), 'lesson_plan', 'lesplan_overview', ['overview_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint(None, 'lesplan_request', type_='foreignkey')
    op.drop_constraint(None, 'lesplan_request', type_='foreignkey')
    op.create_foreign_key(op.f('lesplan_request_class_id_fkey'), 'lesplan_request', 'class', ['class_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(op.f('lesplan_request_user_id_fkey'), 'lesplan_request', 'user', ['user_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint(None, 'lesplan_overview', type_='foreignkey')
    op.create_foreign_key(op.f('lesplan_overview_request_id_fkey'), 'lesplan_overview', 'lesplan_request', ['request_id'], ['id'], ondelete='CASCADE')
    op.create_unique_constraint(op.f('uq_lesplan_overview_request_id'), 'lesplan_overview', ['request_id'], postgresql_nulls_not_distinct=False)
    op.alter_column('file', 'extracted_text',
               existing_type=sqlmodel.sql.sqltypes.AutoString(),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.drop_constraint(None, 'class', type_='foreignkey')
    op.create_foreign_key(op.f('class_user_id_fkey'), 'class', 'user', ['user_id'], ['id'], ondelete='CASCADE')
    op.alter_column('class', 'class_notes',
               existing_type=sqlmodel.sql.sqltypes.AutoString(),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.add_column('book_chapter', sa.Column('toets_url', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'book', type_='foreignkey')
    op.create_foreign_key(op.f('fk_book_subject_id_subject'), 'book', 'subjects', ['subject_id'], ['id'], ondelete='SET NULL')
    op.create_table('lesplan_feedback_message',
    sa.Column('id', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('request_id', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('role', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('content', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['request_id'], ['lesplan_request.id'], name=op.f('lesplan_feedback_message_request_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('lesplan_feedback_message_pkey'))
    )
    op.create_index(op.f('ix_lesplan_feedback_message_request_id'), 'lesplan_feedback_message', ['request_id'], unique=False)
    # ### end Alembic commands ###
